/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mitek;

import java.net.URL;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.soap.MessageFactory;
import javax.xml.soap.SOAPBody;
import javax.xml.soap.SOAPConnection;
import javax.xml.soap.SOAPConnectionFactory;
import javax.xml.soap.SOAPElement;
import javax.xml.soap.SOAPEnvelope;
import javax.xml.soap.SOAPMessage;
import javax.xml.soap.SOAPPart;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author Tommy
 */
public class NewJFrame extends javax.swing.JFrame {
    double persen=0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        DefaultTableModel m = (DefaultTableModel) tabledata.getModel();
        m.addColumn("Idpel");
        m.addColumn("Nama");
        
//            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
//            DocumentBuilder db = dbf.newDocumentBuilder();
//            Document doc = db.parse(new URL("http://localhost/tesxml/coba.xml").openStream());
//            
//            doc.getDocumentElement().normalize();
//            
//            NodeList nodes = doc.getElementsByTagName("buku");
//           
//            DefaultTableModel dtm = new DefaultTableModel();
//            //dtm.addColumn("Judul");
//            
//            String judul [] = new String[nodes.getLength()];
//            String pengarang [] = new String[nodes.getLength()];
//            
//            for (int i = 0; i < nodes.getLength(); i++) {
//                Node node = nodes.item(i);
//                
//                if (node.getNodeType() == Node.ELEMENT_NODE) {
//                    Element data = (Element) node;
//                    //System.out.println(data.getElementsByTagName("judul").item(0).getTextContent());
//                    judul[i] = data.getElementsByTagName("judul").item(0).getTextContent();
//                    pengarang[i] = data.getElementsByTagName("harga").item(0).getTextContent();
//                    System.out.println(judul[i]);
//                    
//                }
//                
//                
//            }
//            dtm.addColumn("Judul", judul);
//            dtm.addColumn("Harga", pengarang);
//            tabledata.setModel(dtm);
//           
//            
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabledata = new javax.swing.JTable();
        btnproses = new javax.swing.JButton();
        pgdata = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabledata);

        btnproses.setText("Proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });

        pgdata.setBackground(new java.awt.Color(102, 255, 102));
        pgdata.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pgdata, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnproses))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnproses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pgdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        Runnable runner = new Runnable()
            {
                public void run() {
        

        try {
            pgdata.setString("0%");
            pgdata.setIndeterminate(true);
            SOAPConnectionFactory scp = SOAPConnectionFactory.newInstance();
            SOAPConnection sp = scp.createConnection();

            String url = "http://localhost/tesxml/hello.php";
            
            MessageFactory mfactory  = MessageFactory.newInstance();
            SOAPMessage    smessage  = mfactory.createMessage();
            SOAPPart       spart     = smessage.getSOAPPart();
            
            SOAPEnvelope   senvelope = spart.getEnvelope();
            senvelope.addNamespaceDeclaration("kalimat", url);
    
            SOAPBody sb = senvelope.getBody();
            SOAPElement soapelement = sb.addChildElement("kalimat");
            soapelement.addChildElement("pesan").addTextNode("70839397");
    
            smessage.saveChanges();
    
            SOAPMessage smes = sp.call(smessage, url);
            //String req = smes.getSOAPBody().getElementsByTagName("nama").item(0).getTextContent();
            
            //DefaultTableModel dtm = new DefaultTableModel();
            DefaultTableModel m = (DefaultTableModel) tabledata.getModel();
            NodeList nodes = smes.getSOAPBody().getElementsByTagName("item");
            
            pgdata.setMaximum(nodes.getLength());
            
            pgdata.setIndeterminate(false);
            //pgdata.setStringPainted(true);
            
            int p = nodes.getLength();
            String nama [] = new String[nodes.getLength()];
            String idpel [] = new String[nodes.getLength()];
           
            NumberFormat formatter = new DecimalFormat("#0.0");
            
            for (int i = 0; i < nodes.getLength(); i++) {
                Node node = nodes.item(i);
                
                if (node.getNodeType() == Node.ELEMENT_NODE) {
                    Element data = (Element) node;
                    nama[i] = data.getElementsByTagName("nama").item(0).getTextContent();
                    idpel[i] = data.getElementsByTagName("idpel").item(0).getTextContent();
                    m.addRow(new Object[]{idpel[i], nama[i]});
                    //System.out.println(idpel[i]+" / "+nama[i]);
                    //
                    pgdata.setValue(i);
                    
                    persen = (((i+1.0) / p) * 100);
                    pgdata.setString(""+formatter.format(persen)+"%");
                    
                    //System.out.println(formatter.format(persen)+"%");
                }   
            }
            
//            dtm.addColumn("Idpel", idpel);
//            dtm.addColumn("Nama", nama);
//            tabledata.setModel(dtm);
            //System.out.println(nodes.getLength());
            sp.close();
            
            Thread.sleep(100);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
                        }
            };
            Thread t = new Thread(runner, "Code Executer");
            t.start();
    }//GEN-LAST:event_btnprosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    public void setValue(final int j) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                pgdata.setValue(j);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnproses;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar pgdata;
    private javax.swing.JTable tabledata;
    // End of variables declaration//GEN-END:variables
}
